Repository LikeLionSCH/9th_Pet_Promotion_Front, pull requests merged in 2021-03, with the labels that each got.

#3 환경세팅::create-react-app, redux, devtool setting
  pet_promotion_front/.gitignore
  pet_promotion_front/README.md
  pet_promotion_front/package-lock.json
  pet_promotion_front/package.json
  pet_promotion_front/public/favicon.ico
  pet_promotion_front/public/index.html
  pet_promotion_front/public/logo192.png
  pet_promotion_front/public/logo512.png
  pet_promotion_front/public/manifest.json
  pet_promotion_front/public/robots.txt
  pet_promotion_front/src/components/App.js
  pet_promotion_front/src/components/MainPanel/AuthPanel/Auth.js
  pet_promotion_front/src/components/MainPanel/MainList/MainPetList.js
  pet_promotion_front/src/components/MainPanel/MainPage.js
  pet_promotion_front/src/components/SidePanel/SideMenu.js
  pet_promotion_front/src/index.js
  pet_promotion_front/src/redux/actions/auth_action.js
  pet_promotion_front/src/redux/actions/types.js
  pet_promotion_front/src/redux/reducers/auth_reducer.js
  pet_promotion_front/src/redux/reducers/index.js
  pet_promotion_front/src/store.js
  pet_promotion_front/yarn.lock
Labels: 개발

#6 개발:: Components Config
  pet_promotion_front/src/components/MainPanel/Animal/AnimalDetail/AnimalDetailMain.js
  pet_promotion_front/src/components/MainPanel/Animal/AnimalDetail/AnimalDetailProfile.js
  pet_promotion_front/src/components/MainPanel/Animal/AnimalPost/AnimalPostComment.js
  pet_promotion_front/src/components/MainPanel/Animal/AnimalPost/AnimalPostCreate.js
  pet_promotion_front/src/components/MainPanel/Animal/AnimalPost/AnimalPostDetail.js
  pet_promotion_front/src/components/MainPanel/Animal/AnimalPost/AnimalPostMain.js
  pet_promotion_front/src/components/MainPanel/AuthPanel/Auth.js
  pet_promotion_front/src/components/MainPanel/AuthPanel/LoginInput.js
  pet_promotion_front/src/components/MainPanel/MainList/MainBestList.js
  pet_promotion_front/src/components/MainPanel/MainList/MainPetList.js
  pet_promotion_front/src/components/MainPanel/User/UserDetail.js
  pet_promotion_front/src/components/MainPanel/User/UserMain.js
Labels: 개발

#10 개발:: Link to, Component 결합
  pet_promotion_front/src/components/MainPanel/Animal/AnimalDetail/AnimalDetailMain.js
  pet_promotion_front/src/components/MainPanel/Animal/AnimalDetail/AnimalDetailProfile.js
  pet_promotion_front/src/components/MainPanel/Animal/AnimalPost/AnimalPostComment.js
  pet_promotion_front/src/components/MainPanel/Animal/AnimalPost/AnimalPostCreate.js
  pet_promotion_front/src/components/MainPanel/Animal/AnimalPost/AnimalPostDetail.js
  pet_promotion_front/src/components/MainPanel/Animal/AnimalPost/AnimalPostMain.js
  pet_promotion_front/src/components/MainPanel/AuthPanel/LoginInput.js
  pet_promotion_front/src/components/MainPanel/MainList/Main.js
  pet_promotion_front/src/components/MainPanel/MainList/MainBestList.js
  pet_promotion_front/src/components/MainPanel/MainList/MainPetList.js
  pet_promotion_front/src/components/MainPanel/User/UserDetail.js
  pet_promotion_front/src/components/MainPanel/User/UserMain.js
  pet_promotion_front/src/components/SidePanel/SideMenu.js
Labels: 개발

#13 규칙:: 명세서 추가
  README.md
Labels: 규칙

#16 규칙:: 명세서 수정
  README.md
Labels: 규칙

#18 개발 :: User API connection, Router fix
  pet_promotion_front/package-lock.json
  pet_promotion_front/package.json
  pet_promotion_front/src/Api/UserApi.js
  pet_promotion_front/src/components/App.js
  pet_promotion_front/src/components/MainPanel/AuthPanel/LoginInput.js
  pet_promotion_front/src/components/MainPanel/MainList/Main.js
  pet_promotion_front/src/index.js
  pet_promotion_front/src/redux/reducers/auth_reducer.js
  pet_promotion_front/yarn.lock
Labels: 개발, 로직

#20 개발::Router Fix
  pet_promotion_front/src/components/App.js
Labels: 개발, 로직, 버그

#26 개발 :: AnimalPostMain style
  pet_promotion_front/src/components/MainPanel/Animal/AnimalPost/AnimalPostComment.js
  pet_promotion_front/src/components/MainPanel/Animal/AnimalPost/AnimalPostDetail.js
  pet_promotion_front/src/components/MainPanel/Animal/AnimalPost/AnimalPostMain.js
  pet_promotion_front/src/components/MainPanel/AuthPanel/LoginInput.js
Labels: 개발

#29 개발:: main.js 재스타일링
  pet_promotion_front/src/components/MainPanel/AuthPanel/Auth.js
  pet_promotion_front/src/components/MainPanel/AuthPanel/LoginInput.js
  pet_promotion_front/src/index.css
Labels: 개발

#32 개발 :: MainPetList.js 스타일링
  pet_promotion_front/src/components/App.js
  pet_promotion_front/src/components/MainPanel/MainList/MainBestList.js
  pet_promotion_front/src/components/MainPanel/MainList/MainPetList.js
  pet_promotion_front/src/components/MainPanel/MainList/Maintest.js
  pet_promotion_front/src/components/assets/Images/doobu2.jpg
Labels: 개발

#34 개발 :: Side Burger Menu 구현 (Mactto)
  pet_promotion_front/package-lock.json
  pet_promotion_front/package.json
  pet_promotion_front/src/components/MainPanel/MainList/Main.js
  pet_promotion_front/src/components/SidePanel/SideMenu.js
  pet_promotion_front/src/components/assets/css/style.css
Labels: 개발

#36 개발 :: Maintest.js 수정, Header 추가
  pet_promotion_front/package-lock.json
  pet_promotion_front/src/components/Header/Header.js
  pet_promotion_front/src/components/MainPanel/Animal/AnimalDetail/AnimalDetailMain.js
  pet_promotion_front/src/components/MainPanel/Animal/AnimalPost/AnimalPostMain.js
  pet_promotion_front/src/components/MainPanel/MainList/Main.js
  pet_promotion_front/src/components/MainPanel/MainList/MainBestList.js
  pet_promotion_front/src/components/MainPanel/MainList/MainPetList.js
  pet_promotion_front/src/components/MainPanel/MainList/Maintest.js
  pet_promotion_front/src/index.css
  pet_promotion_front/src/index.js
  pet_promotion_front/yarn.lock
Labels: 개발

#38 스타일 :: Index.css
  pet_promotion_front/src/index.css
Labels: 개발, 스타일

#41 수정 :: 버거랑 헤더메뉴 중간 공백 문제 수정
  pet_promotion_front/src/components/MainPanel/MainList/Main.js
  pet_promotion_front/src/components/MainPanel/MainList/MainBestList.js
  pet_promotion_front/src/components/MainPanel/MainList/Maintest.js
  pet_promotion_front/src/components/assets/css/style.css
Labels: 버그

#46 개발 :: Header 제거, SideBar 스타일링
  pet_promotion_front/src/components/MainPanel/Animal/AnimalDetail/AnimalDetailMain.js
  pet_promotion_front/src/components/MainPanel/Animal/AnimalPost/AnimalPostMain.js
  pet_promotion_front/src/components/MainPanel/MainList/Main.js
  pet_promotion_front/src/components/MainPanel/MainList/MainBestList.js
  pet_promotion_front/src/components/MainPanel/MainList/MainPetList.js
  pet_promotion_front/src/components/MainPanel/MainList/Maintest.js
  pet_promotion_front/src/components/SidePanel/SideMenu.js
  pet_promotion_front/src/components/assets/Images/test.jpg
  pet_promotion_front/src/components/assets/Images/test2.jpg
  pet_promotion_front/src/components/assets/css/style.css
Labels: 개발, 스타일

#48 개발 스타일 :: 글씨체 넥슨으로 변경
  pet_promotion_front/src/components/App.js
  pet_promotion_front/src/components/MainPanel/Animal/AnimalDetail/AnimalDetailProfile.js
  pet_promotion_front/src/components/MainPanel/Animal/AnimalPost/AnimalPostComment.js
  pet_promotion_front/src/components/MainPanel/Animal/AnimalPost/AnimalPostDetail.js
  pet_promotion_front/src/components/MainPanel/AuthPanel/LoginInput.js
  pet_promotion_front/src/components/MainPanel/MainList/MainBestList.js
  pet_promotion_front/src/components/MainPanel/MainList/MainPetList.js
  pet_promotion_front/src/components/SidePanel/SideMenu.js
  pet_promotion_front/src/components/assets/css/style.css
  pet_promotion_front/src/index.css
Labels: 개발, 스타일

#50 개발:: 웹앱Test
  pet_promotion_front/src/components/MainPanel/MainList/Main.js
  pet_promotion_front/src/components/assets/css/style.css
Labels: 개발, 스타일
